const data = [
    {
        id: 1,
        name: 'angular',
        image: 'images/angular.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 2,
        name: 'angular',
        image: 'images/angular.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 3,
        name: 'css',
        image: 'images/css.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 4,
        name: 'css',
        image: 'images/css.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 5,
        name: 'github',
        image: 'images/github.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 6,
        name: 'github',
        image: 'images/github.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 7,
        name: 'gulp',
        image: 'images/gulp.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 8,
        name: 'gulp',
        image: 'images/gulp.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 9,
        name: 'html',
        image: 'images/html.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 10,
        name: 'html',
        image: 'images/html.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 11,
        name: 'java',
        image: 'images/java.jpg',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 12,
        name: 'java',
        image: 'images/java.jpg',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 13,
        name: 'php',
        image: 'images/php.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 14,
        name: 'php',
        image: 'images/php.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 15,
        name: 'react',
        image: 'images/react.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 16,
        name: 'react',
        image: 'images/react.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 17,
        name: 'swift',
        image: 'images/swift.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 18,
        name: 'swift',
        image: 'images/swift.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 19,
        name: 'vue',
        image: 'images/vue.png',
        isWaiting: false,
        isDone: false,
    },
    {
        id: 20,
        name: 'vue',
        image: 'images/vue.png',
        isWaiting: false,
        isDone: false,
    },
]



export default data